server:
  port: 8761
  tomcat:
    uri-encoding: UTF-8
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
spring:
  security:
    user:
      name: user
      password: password123