server:
  port: 8181
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: first-love-user
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
